- name: setup rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq server
    ansible.builtin.package: 
     name: rabbitmq-server
     state: present

  - name: start and enable server
    ansible.builtin.service:
      name: rabbitmq
      state: started
      enabled: yes

  - name: create and provide permissions to user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: changeme
      permissions: 
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present